### ISSUE TITLE
[Design] [FE] Create New organization Form

### ISSUE THREAD

**Issue by jessieh9** [spatialneuroscience/Concord#15]
Currently, on Figma we have no new organization form. 
1. Create a new organization form with the following information
             - Name of the organization
             - Who the organization is led by
             - Brief description of the org
 
You can follow the New Project form in the Figma already created for layout inspiration.
Create the form in the Main Pages section.

![Image](https://github.com/user-attachments/assets/a4818fa7-538a-480c-bbda-84f7ce172c42)

Figma Link: https://www.figma.com/team_invite/redeem/m7USct7pyXUSdm1R6BbS9B

**Comment by AstonKiChan** [comment]
Should be done now. @jessieh9

**Comment by jessieh9** [comment]
LGTM!
