### ISSUE TITLE
[Page] [FE] RA Summary

### ISSUE THREAD

**Issue by jessieh9** [spatialneuroscience/Concord#27]
1. Create an RA Summary Page and add in a short description. Remove to-do and notes column. Extend the weeks 1-10.
![Image](https://github.com/user-attachments/assets/1f2b6272-0b58-4a41-8b4d-31ccd488542f)

2. Just create a route for it for now in App.js, don't need to add anything to the sidebar. 
3. Use hardcoded or test data for now. 

Check out Chakra UI Tables https://v2.chakra-ui.com/docs/components/table
Figma Link: https://www.figma.com/team_invite/redeem/m7USct7pyXUSdm1R6BbS9B

**Comment by AstonKiChan** [comment]
Should be done now, up for review.
