### ISSUE TITLE
[Data] [BE] Populate database with test data

### ISSUE THREAD

**Issue by jessieh9** [spatialneuroscience/Concord#29]
Populate the database with some test data. Make it so that we can visibily see that it is test data so in the future we can remove it.
i.e "Test1 Organization" , "Testing: update the project name task", "user 1 test", "project 1 test", etc...

You will make test data in the following tables. Contact Richard for any foreign constraints.
1. Organizations
2. Projects
3. Tasks
4. Users

Refer to the database schema for adding them in. 
You might also want to reference this spreadsheet : https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vT8l9l3h0_MPRxbnGLX-9qfJ0zAfJGkx7OfQUdCSjURDcKZQtEkHGIWiYwzbbG_aRhEtFRS1Q7Nx9wO/pubhtml?widget=true&amp;headers=false&rm=minimal&zoomScale=89

**Comment by Will15800** [comment]
I added some test data to the tables, can you check please?

**Comment by jessieh9** [comment]
Thank you Will, looks good!
